language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: treZshVEQEtUybfkMFvFVJwFJup9bF/1yX5Z0ImohmpK2y0+Gj5Y1sCuMmRKLoM1Ry32zMXU6pBrR65e26R9B4cuDgVdOECCDBHbXql1/f4W2sqf9uatvu6Gv+bgDUBudVGWGntXwMfzB3izsVDxgGPSBP63VZnCRCt4YkonqFaOYD6jygxTus+Z/YWTbbTEF2qquBypf0eDg4DKt91j3uUtRLZjtSCCYzZK1g/npI3vRukhX8GG1/hiIaFXRlV6xtk40ejKoTLCeRAogsX9KKLN6TP7Q4BYwN2UfY+JycnRzUzxyAp9idXVcFvtRNfsEjtUKL1qNzR/HdIY5YuPzEgK+gBSV6X6tq6MD/JCQAqYfnDxtm/PwRYUXDymEN4/iyTTLQonLOzffejneEaxk23W4etEUESwChKKAUsv9ptdrGCgR27RD/z7pEwBAbxTOECwaDqa2JmNFmrWTrn9XiaJFsf/S9/CN0jUZaAVK2YyvPkxcLU31K8f9RN35jiTDUGjVB65c9UQMUTLhCwHQmgivnL/I+zXip1mB2Qyc4FxuM3fPDPS9LF1NAOoDjFhQtdCGnS0Tjl4d04PrRSlBkjs4xM83Rob2NngvmYm4YbLXKuhIY0C7rzIzx1XsK+NjMIA2WonHl4YCWfVL+URFPkhA5OLD0p7M7VT8IiqMQM=
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true
    repo: wjwillemse/solvency2-data
    python: 3.7
