language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: 4BT5knTIbR7ohx8vhm6yIgFgAbw8boaEc6O+IwlDJYg54FSFA03t7gMd2z2zxCV/ICmA+if1UcKfPSIYiGse4rPVgdI2hJA6tuaLOx0r/4heAgTklo7T9nqQPsz9IvjDn1Q94ZdjSaLmawjPkB94ApeC4VjW++TuFgexE0PROrFMN/ss+lUJ2xJf9q4/3E6sPtx0dYspYFj8Nv+d0OYxsyf/pM3VNzRY+NInirChb3ppKcYIJe3nAAr0oKOCce4QioHmqUdk/G62QCAfq7KpUoxmMg6igUTN/LgIfN4KUm+qYmkOJAEt8XfKW001FkvkepOJvqDhnUKQHBRBPxS2bS/vyBm8FD1SAfzWuWuTECaNsNkGDgh2xLHzqmjYs82hImA+3SjdoN4EtZhPxEBMq7c857N7rXe2cPQiIwslvW4+Dxm86+s05jDX8+45v6MLex167m2MygtwInQW8BpFEIHwNH8CnxX+f3483RjrwksWg0VpqC74+eNntv4imZ4/qMdWl3oX3AewXlpc60g6P+bp2hMoHBINCuvGm4LzFDQORW9XXbzzPx45fnFDWAn3uZ3goe4NbarHm3s/JgMVzZaseQ6TskOhZSzAsMiYMvRNxrPzoTMOQ4sTJo74TQOgryerrSIg7QrVq20gUjRTSADmRPel/IPRrKSVTbhlKYQ=
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true
    repo: DeNederlandscheBank/solvency2-data
    python: 3.7
