language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: "g+MAIvf0ygHUvmZE27gVvTS4xaWeVjCpAuwJi1HxnbImBBkeU7sqvxuGYn4f90jm4njghCHtRlK51cZQUqi2OTn1n0QgtVwbR3WSuOzzKcsASM8OG4Vn/yYZuuMSsjoUi0rW2Ewc2HOVEPuqRY7W4/FgyVICdfvNRTF/Uv/FVXL/4vC9fLdnnNLL3NDjoOOHVD0AB4QOFqWnr35j2KYwWpyE/8RsfJ2yBXTqpA2tQYzRkY/CQbWw4NfHQr0YEev2svSlzuppY+Rx76E4iDGlzuqH26qIOIbAPAnPEJiXsQ34K+j+QGwwPoEKVQpQT3GEmW8ymbhbDtJ4fqu+NsyvdhK2ECCBtGo+j0d9mWZ+OPwQ1gGvwY8hOiD6nZs3zPS+O6V/jikoyJqND+eVUk/+i2zIzj3I62p6uUO9K9Tyt6ip1NOwMjY4PSiWEKZg54bWcWORZANYZR3thalG0ayySSEUfIOuRQX22V1NhrVfXMHRGcq5Vs3aHYaD9XddDdXOdtS144pgmKKYoqMRIUFlhy8fmOuroaEfEQgQmTjt9VK6TfpNoYrzq/aAMBHpDP0Sr+62KhLOWgoKHWFXKheI8g9KM8auaejVStjEkuQSUqlsNKn3Pr+uXXD/A1lb0AMu4kJ2wFMm87Do0gcFRHFdjg2hjh1kRxmgboC5T10dyHQ="
  skip_existing: true
  on:
    tags: true
    repo: DeNederlandscheBank/solvency2-data
    python: 3.7
