language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: XsDpwTzx3CGPUqqH4egOcVQO1mc4HTQo2ZlYLgR37tqbPXBzMu6j7aznRRnFQf51L+vCMcNvnk8DxFu1uEEo7+TIZgGOZmRyiE0LOZIxS8hvGAOKaHt72rOwC8Z603Q7WA7nuxYf9uBmaq+rBV1ewQkkOhqfiLz/WVmtdhJu5nmdGrKWtfBerBy/RspbF1+8/APctUeUtifuOItzS0QHjUc87LOlMNuq60gcLxg+9eOSUQi9HC9dwmxRqWdKk11hcvF76LiX4H4csJKVkyLa5bt6u55Znax5eqFwUXyecG/PHb6HVe2EzYlb9oSmb76xY3HAXybpRO5uv6DtQj4UKNKOz+3nTRSljjw6YRlCz6Jp5ERZNSS7Q1j/oRK+juqVxSPrqXcOtOOXWfQjJ0Kgv8Wg7v5OBDPeOidrQpDfppIAxJITXY1tyEatoQ/qvuu3csjNKWJ3jaRJZDyAq0BfuV2e1GeO1+8ptzUQbLDTchH6KM6k/SowJnwWJW4nQDOhQngIoiiaFUsWu1MZlHAnCjgC6pDCBKMfU1ogs0aZeLdySMPYPJuzHgy1oytJB/1gMpeJPzZoFKvFjJil538ChFUyUQItHHmnVcftkWuYY4XP16tUjvz58FCOM+13YmxzncsrXLMwLG0qxF9JCyTu9YRfNJf0zjWwbK6b/YKc+gA=
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true
    repo: wjwillemse/solvency2-data
    python: 3.7
