language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  skip_existing: true
  provider: pypi
  distributions: sdist bdist_wheel
  user: wjwillemse
  on:
    tags: true
    repo: DeNederlandscheBank/solvency2-data
    python: 3.7
env:
  global:
    secure: xC2LJ3f02VCT7jNyKpWPiZLyhkIIIuJZ+/dK69WOwanhNVIafV918+OW3hePh5P4q3X1egez8W70ySikv3xk5AhUvBDwSs1j3OGjYHEA5MzLHTeRxpBPIL8Lin11GOgfw1yU40z9TqtmgZTsevoPibPrwsaKpagTDzhsZEGIwHb1PheAz9lKpbpzEd4ZQRKdQbwpiT3yAPnfFBCesoItKstROexHzKFbJ9ObIW/MXDl6ig0XHF8oRivkJ8ypT+fKRw9B0MwD9NNI8dPJirLzI7u1H5Gp4uqTY7pLbOGO6LQ6iGCpw9gKutDbHHePVfvBdPRu6WXPBjZoufkWDdnruJVXMGM6CuIEhDmKdrm7HUS/IocT55sNj5DZXHNAAyR2lG4bOETqLJgkZtTOFy4bujvXc+YSeQRKTKhS85hW+XOzwNoW2cYztLYep+lEMeFqAXLtkEFe6V00zgaDewrum9uSpUzUV2SPigGxBHRJSHs3wSHF8zpemAgPJJQLjFOBbCdpZN/v9RKt/NBmRDoOG011lnzimqoo1T2RHzb5g8iyQtGJBo+uJBCrvys7gTBaKSULMLQhBb7TpgrLfTuT7Fmw/LmUYRkzeyipJUuFu5S0HsTylscwx4VIiY2vhTx3CBuu/vvvaZrjZKAAURsnHPV9z+PxW3Izf2jrpPuCjQw=
