language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: dihi+ef2dn2Ow+ru3NN4GyCc9802kBY1YJkIPbMpEB2TLVWnLtHEZuMdScwaELi4WfSV0DfExD7Zs76Jm4vVj7iN0/ZtMOdsv4k1n4A+JKsCPykOJ64NmYBCuIjB0RnCbol/MGqWBrT3mV9yoSgS2B6dSFJyNBpcz7b4YuD39VhNW1DQ1OAFAIo61W7HnsBRo7gsRI5eh2kCLQKTzB+CqN9miEHfJO/n5mIc5Qy02yLAiTUQYazQqTWbTdh/U8+5zYWoBC/4W8OtKOTcgM6ibU0BrkzHl1xokIo7Mg1rw6FS8vzKcOClmtFdPL4pbjS/PcCscrbCpHxsvIB7JAokXGa83F0pw/poCe+8tbFjUQpVX1ilyPuaUnEqvLis7ILNJlhzxNqo3PGvs1ARSAOwR+4EeVkZSNbEmSqt6CM3j43YIUV8Ab9HUT2GIsi70uddMAf+cHXbvxhvg7vG46/FQRoqbXiPuKJb+vMKUssBBRkpo5cLgVaotb7YjDV8nv8QISPyeCDIXfO7XRgXAFdRiY8qoDuK57m+2tPy808aGlzgvfl2vjJExvTYKZqZId/5QJviwLYouTjifmWesHdE5EIT9M5GqESwzY3W73xSCBV+OI7Ru5iiC4TBrR3AJXZeePew6AuoCiCD76SZgXZ22kOEPUtwc7UPqJ2HiPLw4Yc=
  skip_cleanup: true
  on:
    tags: true
    repo: DeNederlandscheBank/solvency2-data
    python: 3.7
